import Vue from 'vue'
import VueRouter from 'vue-router'

Vue.use(VueRouter)

const routes = [
	{ path: '/', name: 'home', component: () => import('../views/Home.vue') },
	{ path: '/button', name: 'button', component: () => import('../views/button.vue') },
	{ path: '/cell', name: 'cell', component: () => import('../views/cell.vue') },
	{ path: '/icon', name: 'icon', component: () => import('../views/icon.vue') },
	{ path: '/image', name: 'image', component: () => import('../views/image.vue') },
	{ path: '/col', name: 'col', component: () => import('../views/col.vue') },
	{ path: '/popup', name: 'popup', component: () => import('../views/popup.vue') },
	{ path: '/style', name: 'style', component: () => import('../views/style.vue') },
	{ path: '/calendar', name: 'calendar', component: () => import('../views/calendar.vue') },
	{ path: '/checkbox', name: 'checkbox', component: () => import('../views/checkbox.vue') },
	{ path: '/datetimepicker', name: 'datetimepicker', component: () => import('../views/datetimepicker.vue') },
	{ path: '/field', name: 'field', component: () => import('../views/field.vue') },
	{ path: '/form', name: 'form', component: () => import('../views/form.vue') },
	{ path: '/numberkeyboard', name: 'numberkeyboard', component: () => import('../views/numberkeyboard.vue') },
	{ path: '/passwordinput', name: 'passwordinput', component: () => import('../views/passwordinput.vue') },
	{ path: '/picker', name: 'picker', component: () => import('../views/picker.vue') },
	{ path: '/radio', name: 'radio', component: () => import('../views/radio.vue') },
	{ path: '/rate', name: 'rate', component: () => import('../views/rate.vue') },
	{ path: '/search', name: 'search', component: () => import('../views/search.vue') },
	{ path: '/slider', name: 'slider', component: () => import('../views/slider.vue') },
	{ path: '/stepper', name: 'stepper', component: () => import('../views/stepper.vue') },
	{ path: '/switch', name: 'switch', component: () => import('../views/switch.vue') },
	{ path: '/uploader', name: 'uploader', component: () => import('../views/uploader.vue') },
	{ path: '/actionsheet', name: 'actionsheet', component: () => import('../views/actionsheet.vue') },
	{ path: '/dialog', name: 'dialog', component: () => import('../views/dialog.vue') },
	{ path: '/dropdownmenu', name: 'dropdownmenu', component: () => import('../views/dropdownmenu.vue') },
	{ path: '/loading', name: 'loading', component: () => import('../views/loading.vue') },
	{ path: '/notify', name: 'notify', component: () => import('../views/notify.vue') },
	{ path: '/overlay', name: 'overlay', component: () => import('../views/overlay.vue') },
	{ path: '/pullrefresh', name: 'pullrefresh', component: () => import('../views/pullrefresh.vue') },
	{ path: '/swipecell', name: 'swipecell', component: () => import('../views/swipecell.vue') },
	{ path: '/toast', name: 'toast', component: () => import('../views/toast.vue') },
	{ path: '/circle', name: 'circle', component: () => import('../views/circle.vue') },
	{ path: '/collapse', name: 'collapse', component: () => import('../views/collapse.vue') },
	{ path: '/countdown', name: 'countdown', component: () => import('../views/countdown.vue') },
	{ path: '/divider', name: 'divider', component: () => import('../views/divider.vue') },
	{ path: '/imagepreview', name: 'imagepreview', component: () => import('../views/imagepreview.vue') },
	{ path: '/lazyload', name: 'lazyload', component: () => import('../views/lazyload.vue') },
	{ path: '/list', name: 'list', component: () => import('../views/list.vue') },
	{ path: '/noticebar', name: 'noticebar', component: () => import('../views/noticebar.vue') },
	{ path: '/panel', name: 'panel', component: () => import('../views/panel.vue') },
	{ path: '/progress', name: 'progress', component: () => import('../views/progress.vue') },
	{ path: '/skeleton', name: 'skeleton', component: () => import('../views/skeleton.vue') },
	{ path: '/steps', name: 'steps', component: () => import('../views/steps.vue') },
	{ path: '/sticky', name: 'sticky', component: () => import('../views/sticky.vue') },
	{ path: '/swipe', name: 'swipe', component: () => import('../views/swipe.vue') },
	{ path: '/tag', name: 'tag', component: () => import('../views/tag.vue') },
	{ path: '/grid', name: 'grid', component: () => import('../views/grid.vue') },
	{ path: '/indexbar', name: 'indexbar', component: () => import('../views/indexbar.vue') },
	{ path: '/navbar', name: 'navbar', component: () => import('../views/navbar.vue') },
	{ path: '/pagination', name: 'pagination', component: () => import('../views/pagination.vue') },
	{ path: '/sidebar', name: 'sidebar', component: () => import('../views/sidebar.vue') },
	{ path: '/tab', name: 'tab', component: () => import('../views/tab.vue') },
	{ path: '/tabbar', name: 'tabbar', component: () => import('../views/tabbar.vue') },
	{ path: '/treeselect', name: 'treeselect', component: () => import('../views/treeselect.vue') },
	{ path: '/addressedit', name: 'addressedit', component: () => import('../views/addressedit.vue') },
	{ path: '/addresslist', name: 'addresslist', component: () => import('../views/addresslist.vue') },
	{ path: '/area', name: 'area', component: () => import('../views/area.vue') },
	{ path: '/card', name: 'card', component: () => import('../views/card.vue') },
	{ path: '/contactcard', name: 'contactcard', component: () => import('../views/contactcard.vue') },
	{ path: '/couponlist', name: 'couponlist', component: () => import('../views/couponlist.vue') },
	{ path: '/goodsaction', name: 'goodsaction', component: () => import('../views/goodsaction.vue') },
	{ path: '/submitbar', name: 'submitbar', component: () => import('../views/submitbar.vue') },
	{ path: '/sku', name: 'sku', component: () => import('../views/sku.vue') },
	{ path: '/switchcell', name: 'switchcell', component: () => import('../views/switchcell.vue') },
]

const router = new VueRouter({
  routes
})

export default router
